[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

[lint]
exclude_lints = ["mixed-case-variable", "mixed-case-function","screaming-snake-case-const", "screaming-snake-case-immutable"]
