[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/solidity'
cache_path  = 'cache_forge'
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@kleros/=node_modules/@kleros/',
    'forge-std/=lib/forge-std/src/',
    'src/=contracts/',
    'contracts/=contracts/'
]

[lint]
exclude_lints = [
    "mixed-case-variable",
    "mixed-case-function",
    "screaming-snake-case-const",
    "screaming-snake-case-immutable"
]
