name: DApp CI

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - packages/dapp/**
  push:
    branches:
      - main
      - develop
    paths:
      - packages/dapp/**

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - name: Set up node using nvm
        uses: dcodeIO/setup-node-nvm@v5
        with:
          node-version: 18

      # - name: "Copy config"
      #   run: |
      #     mv ./evm/.env.github ./evm/.env
      #     echo "::debug::$(less .env)"

      - name: Install the dependencies
        run: pnpm install

      - name: Lint the code
        run: pnpm dapp:lint

      - name: Add lint summary
        run: |
          echo "## Lint results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: Test the code and generate the coverage report
        run: pnpm dapp:test

      - name: Add test summary
        run: |
          echo "## Test results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
